config/routes.rb
Killthebugs::Application.routes.draw do

  get 'fragments/shared' => 'fragments#shared', :as => "shared_fragments"

  get 'share_fragment/:fragment_id/to/:user_id' => 'fragments#share', :as => "share_fragment"

  get 'unshare_fragment/:fragment_id/to/:user_id' => 'fragments#unshare', :as => "unshare_fragment"

  resources :fragments

  resource :settings, only: [:edit, :update]

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :fragments, only: [:create]
    end
  end

  get "welcome/index"

  get "/f/:hashie" => "fragments#hashie", :as => "fragment_by_hashie"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root to: 'fragments#new'
end

app/models/fragment.rb
class Fragment < ActiveRecord::Base

  validates_presence_of :code, :user_id, :language
  validates_uniqueness_of :title, :scope => :user_id
  validates_uniqueness_of :hashie

  attr_accessible :code, :has_bugs, :is_public, :title, :language
  has_many :sharings
  has_many :users, :through => :sharings
  belongs_to :author, class_name: "User", foreign_key: :user_id, inverse_of: :own_fragments

  before_create :auto_title
  after_create :create_hashie

  # strip useless symbols that browsers may send
  def code=(val)
    write_attribute(:code, val.delete("\r"))
  end

  private

  def auto_title
    if title.blank?
      self.title = code.lines.first
    end
  end

  def create_hashie
    self.hashie = SecureRandom.hex(16)
    self.save!
  end
end

app/models/sharing.rb
class Sharing < ActiveRecord::Base

  attr_accessible :user_id, :fragment_id

  validates_uniqueness_of :fragment_id, :scope => :user_id
  
  belongs_to :user
  belongs_to :fragment

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :sharings
  has_many :fragments, :through => :sharings
  has_many :own_fragments, class_name: "Fragment", foreign_key: :user_id

  serialize :settings, ActiveRecord::Coders::Hstore

  validates :api_token, uniqueness: {allow_nil: true}

  after_create :initialize_settings

  def generate_api_token!
    self.api_token = SecureRandom.hex(16) + id.to_s
    self.save!
  end

  private

  def initialize_settings
    self.settings ||= { default_language: "ruby" }
    self.save!
  end
end

app/controllers/api/v1/fragments_controller.rb
module API
  module V1
    class FragmentsController < ApplicationController
      def create
        user = User.where(api_token: params[:api_token]).first

        if user.nil?
          head :unauthorized    # 401
          return
        end

        fragment = user.own_fragments.new params[:fragment]
        fragment.language ||= user.settings["default_language"]
        if fragment.save
          render text: fragment_path(fragment), status: :created # 201
        else
          head :not_acceptable  # 406
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def can_edit_fragment(fragment_id)

    return true if Fragment.find(fragment_id).user_id == current_user.id
    return false
    
  end
end

app/controllers/fragments_controller.rb
class FragmentsController < ApplicationController

  before_filter :authenticate_user!, :except => [:hashie]

  def hashie
    @fragment = Fragment.find_by_hashie(params[:hashie])
  end

  def share
    @sharing = Sharing.new(:user_id => params[:user_id], :fragment_id => params[:fragment_id])

    if @sharing.save
      redirect_to :fragments, :notice => "Code fragment shared!"
    else
      redirect_to :fragments, :notice => "Cant' share fragment! May be it's already shared"
    end
  end

  def unshare
    @sharings = Sharing.where(:user_id => params[:user_id], :fragment_id => params[:fragment_id])

    if @sharings.destroy_all
      redirect_to :fragments, :notice => "This sharing removed!"
    else
      redirect_to :fragments, :notice => "Cant' remove sharing! May be it's already deleted"
    end
  end

  def shared
    @fragments = current_user.fragments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fragments }
    end
  end

  # GET /fragments
  # GET /fragments.json
  def index
    @fragments = Fragment.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fragments }
    end
  end

  # GET /fragments/1
  # GET /fragments/1.json
  def show
    @fragment = Fragment.find(params[:id])

    if User.find(@fragment.user_id).id == current_user.id
      render :show and return
    elsif @fragment.users.include?(current_user)
      render :show_shared and return
    else
      redirect_to root_path, :alert => "Sorry, you have no access to this page" and return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fragment }
    end
  end

  # GET /fragments/new
  # GET /fragments/new.json
  def new
    @fragment = Fragment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fragment }
    end
  end

  # GET /fragments/1/edit
  def edit
    if can_edit_fragment(params[:id])
      @fragment = Fragment.find(params[:id])
    else
      redirect_to root_path, :alert => "Sorry, you cant' edit this code fragment!"
    end
  end

  # POST /fragments
  # POST /fragments.json
  def create
    @fragment = current_user.own_fragments.new params[:fragment]

    respond_to do |format|
      if @fragment.save
        format.html { redirect_to fragment_path(@fragment), notice: 'Fragment was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /fragments/1
  # PUT /fragments/1.json
  def update

    if can_edit_fragment(params[:id])

      @fragment = Fragment.find(params[:id])

      respond_to do |format|
        if @fragment.update_attributes(params[:fragment])
          format.html { redirect_to fragment_path(@fragment), notice: 'Fragment was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    else

      redirect_to root_path, :alert => "Sorry, you cant' update this code fragment!"

    end
  end

  # DELETE /fragments/1
  # DELETE /fragments/1.json
  def destroy
    @fragment = Fragment.find(params[:id])
    @fragment.destroy

    @sharings = Sharing.where(:fragment_id => params[:id]).destroy_all

    respond_to do |format|
      format.html { redirect_to fragments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def edit
    @settings = current_user.settings
  end

  def update
    current_user.settings = params[:settings]
    current_user.save
    redirect_to root_path, notice: "Settings saved"
  end
end

app/controllers/users_contoller.rb
class UsersController < ApplicationController

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def languages
    lexers = Rouge::Lexer.all
    names = lexers.map { |i| i.name.split('::').last }
    tags = lexers.map &:tag
    names.zip(tags).sort_by {|i| i[0]}
  end
end

app/helpers/fragments_helper.rb
module FragmentsHelper
  def highlighted_code(fragment)
    # initializing formatter here to pass options
    formatter = Rouge::Formatters::HTML.new line_numbers: true
    raw Rouge.highlight(fragment.code, fragment.language, formatter)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fragments/_form.html.haml
= form_for @fragment, :html => { :class => 'form-horizontal' } do |f|
  - if @fragment.errors.any?
    #error_explanation
      %p= "#{pluralize(@fragment.errors.count, "error")} prohibited this fragment from being saved:"
      %ul
        - @fragment.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :title, "Title this code", :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :language, "What language is it?", :class => 'control-label'
    .controls
      = f.select :language, options_for_select(languages, @fragment.language || current_user.settings["default_language"])
  .control-group
    = f.label :is_public, "This should be public?", :class => 'control-label'
    .controls
      = f.check_box :is_public, :class => 'check_box'
  .control-group
    = f.label :has_bugs, "Is it buggy?", :class => 'control-label'
    .controls
      = f.check_box :has_bugs, :class => 'check_box'
  .control-group
    = f.label :code, "Place your code here:", :class => 'control-label'
    .controls
      = f.text_area :code, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), fragments_path, :class => 'btn'

app/views/fragments/edit.html.haml
- model_class = Fragment
.page-header
  %h3=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/fragments/hashie.html.haml
- unless @fragment.nil?
  - if @fragment.is_public
    %h3= @fragment.title
    %p
      This is
      = @fragment.is_public ? "public" : "private"
      code fragment
      = @fragment.has_bugs ? "with" : "without"
      bug(s)

    = highlighted_code(@fragment)
  - else
    Sorry, but this is not public resource!
- else
  Sorry, but there is no code fragments!

app/views/fragments/index.html.haml
- model_class = Fragment
.page-header
  %h3 My code fragments
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:is_public)
      %th= model_class.human_attribute_name(:has_bugs)
      %th Shared with
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @fragments.each do |fragment|
      %tr
        %td= link_to fragment.title, fragment_path(fragment)
        %td
          - if fragment.is_public
            Yes,
            = link_to "Public link", fragment_by_hashie_path(fragment.hashie)
          - else
            No, private
        %td
          - if fragment.has_bugs
            %span.label.label-warnings
              Yes, bug(s) inside!
          - else
            %span.label.label-info
              No, just snippet
        %td
          - if fragment.users.empty?
            Not shared
          - else
            - fragment.users.each do |user|
              .btn.btn-mini= user.email
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_fragment_path(fragment), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), fragment_path(fragment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_fragment_path, :class => 'btn btn-primary'

app/views/fragments/new.html.haml
- model_class = Fragment
.page-header
  %h3 Create new code fragment
= render :partial => "form"

app/views/fragments/shared.html.haml
- model_class = Fragment
.page-header
  %h3 Code shared with me
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th Author
      %th= model_class.human_attribute_name(:has_bugs)
      %th= model_class.human_attribute_name(:created_at)
  %tbody
    - @fragments.each do |fragment|
      %tr
        %td= link_to fragment.title, fragment_path(fragment)
        %td= User.find(fragment.user_id).email
        %td= fragment.has_bugs
        %td=l fragment.created_at

= link_to t('.new', :default => t("helpers.links.new")), new_fragment_path, :class => 'btn btn-primary'

app/views/fragments/show.html.haml
%h3= @fragment.title
- if @fragment.is_public
  %p
    Use this link to share with all signed in members of KillTheBugs:
    %br/
    <input type=text style="width: 100%" value="#{fragment_by_hashie_url(@fragment.hashie)}"/>
%p
  This is
  = @fragment.is_public ? "public" : "private"
  code fragment
  = @fragment.has_bugs ? "with" : "without"
  bug(s)
- if @fragment.users.empty?
  Not shared yet
- else
  Shared with users (click to remove):
  - @fragment.users.each do |user|
    .btn.btn-mini= link_to user.email, unshare_fragment_path(@fragment.id, user.id)

%p Click at user to invite him:
- (User.all - @fragment.users - [current_user]).each do |user|
  .btn.btn-default.btn-mini= link_to user.email, share_fragment_path(@fragment.id, user.id)
= link_to t('.edit', :default => t("helpers.links.edit")), edit_fragment_path(@fragment), :class => 'btn btn-mini'
= link_to t('.destroy', :default => t("helpers.links.destroy")), fragment_path(@fragment), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
%br/
%br/
= highlighted_code(@fragment)

app/views/fragments/show_shared.html.haml
- model_class = Fragment
%h3= @fragment.title
%p
  This is
  = @fragment.is_public ? "public" : "private"
  code fragment
  = @fragment.has_bugs ? "with" : "without"
  bug(s)

= highlighted_code(@fragment)

- if @fragment.users.empty?
  Not shared yet
- else
  Shared with users:
  - @fragment.users.each do |user|
    .btn.btn-mini= user.email

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Kill The Bugs"
    = csrf_meta_tags
    <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,500&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = javascript_include_tag "application"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    / %link(href="favicon.ico" rel="shortcut icon")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          - if user_signed_in?
            = link_to "Kill The Bugs", fragments_path, :class => "brand"
          - else
            = link_to "Kill The Bugs", root_path, :class => "brand"
          .container.nav-collapse
            %ul.nav.pull-right

              - if user_signed_in?
                %li= link_to "UPLOAD SOME CODE!", new_fragment_path
                %li= link_to "My Code Fragments (#{Fragment.where(:user_id => current_user.id).count})", fragments_path
                %li= link_to "Shared with Me (#{current_user.fragments.count})", shared_fragments_path
                %li= link_to "Settings", edit_settings_path
                %li= link_to "Sign out (#{current_user.email})", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "Sign in!", new_user_session_path
                %li= link_to "Create account", new_user_registration_path


    .container
      = bootstrap_flash
      = yield

app/views/settings/edit.html.haml
= form_tag settings_path, method: :put do
  = label_tag "Default language"
  = select_tag "settings[default_language]", options_for_select(languages, @settings["default_language"])
  %br
  = submit_tag "Save"

app/views/welcome/index.html.haml
%h3 Hello!
%p This is 'Kill The Bugs!' small pastebin-like service for small teams.

%p You can keep code snippets here, share some code fragments with other developers with public links, create private snippets and invite collaborators to help you find bugs/improve you code.

%p Because all you code are not visible for everyone you must create an account and sign in before you start work!